### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 1oglop1** [echonax/Ng2-rc1#1]
Hello, you were the one of people who has blocked my question on stackoverflow, could you please help me improve my question and tell me what would you expect to see there or know?

I could post only 2 links, so one of them is non/working example, I'd like to point to the code error but it's far to difficult to find, otherwise I'd not be asking there.

http://stackoverflow.com/questions/40860825/d3js-svg-firefox-style-properties-html-canvas

Thank you

**Comment by echonax** [comment]
Hello, first of all I would strongly suggest you to read: http://stackoverflow.com/help/how-to-ask

I've casted to close your question for its original state. It seems to be fine now but still could be better. You can provide a fiddle/plunker of your code so we can re-produce the issue without losing time. Because while we try to reproduce your issue, we might lose interest in the problem.

For an example d3 template: http://jsfiddle.net/xg8fLs26/4/

Moreover, if you can narrow-down your code, it would even be better. For example "I think firefox doesn't draw a svg without width but how can I overcome this?". Even this example question is not good because you can google it. But I think you got the idea.

Think that we know nothing about your question. Because we don't. People sometimes assume that something they know about their question is intuitional and miss some very important points.

Hope it helps
